# Generated by Django 4.2.6 on 2025-05-22 06:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0002_profile_experience'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='client_satisfaction',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='profile',
            name='complete_projects',
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
