# Generated by Django 4.2.6 on 2025-05-22 06:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0003_profile_client_satisfaction_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='short_bio',
            field=models.TextField(blank=True),
        ),
    ]
