# Generated by Django 4.2.6 on 2025-05-27 09:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0004_profile_short_bio'),
    ]

    operations = [
        migrations.AddField(
            model_name='skill',
            name='img',
            field=models.ImageField(blank=True, upload_to='images/'),
        ),
    ]
