# Generated by Django 4.2.6 on 2025-05-28 10:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0005_skill_img'),
    ]

    operations = [
        migrations.CreateModel(
            name='Testimonial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('picture', models.ImageField(blank=True, upload_to='images/')),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('job', models.CharField(max_length=200)),
            ],
        ),
    ]
